services:
  # Nginx - Web Server
  nginx:
    container_name: nginx
    image: nginx:1.24 # 1.20 updated 4/19/2024 # 1.18 Updated 8/9/2021
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["core", "all"]
    networks:
      - t3_proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - $DOCKERDIR/logs/ws/nginx:/var/log/nginx
      - $DOCKERDIR/appdata/nginx/nginx.conf:/etc/nginx/nginx.conf
      - $DOCKERDIR/appdata/sites/miswitch/miswitch-api:/usr/share/nginx/html
      - $DOCKERDIR/logs/ws/miswitch/debug.log:/var/www/html/miswitch/debug.log
    labels:
      - "traefik.enable=true"
      # HTTP Routers DASH (non-WordPress)
      - "traefik.http.routers.nginx-miswitch-rtr.entrypoints=websecure"
      - "traefik.http.routers.nginx-miswitch-rtr.rule=Host(`nginx.$DOMAINNAME_WS`)" # crowdsec
      # Middlewares
      - "traefik.http.routers.nginx-miswitch-rtr.middlewares=chain-oauth@file"
      # HTTP Services
      - "traefik.http.routers.nginx-miswitch-rtr.service=nginx-svc"
      - "traefik.http.services.nginx-svc.loadbalancer.server.port=80"